[[redirects]]
  from = "/harper/*"
  to = "https://lucid-hamilton-621142.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/what-cocktail/*"
  to = "https://nifty-wilson-ca5f79.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/potato-quiz/*"
  to = "https://stupefied-pike-070458.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fitworks/*"
  to = "https://gracious-euclid-4f703f.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/the-journal/*"
  to = "https://focused-wilson-bca51b.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/dust-bunny/*"
  to = "https://fervent-heyrovsky-990178.netlify.app/:splat"
  status = 200
  force = true